name: PyCI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: Gr1N/setup-poetry@v7
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: poetry-${{ hashFiles('poetry.lock') }}
    - run: poetry --version
    - name: Install dependencies
      run: poetry install
    - name: Lint
      run: make lint
    - name: Test
      run: make test
